function plotCharacteristics_CDNozzle(Fig,Node,CPlus,CMinus,NozzleNodes, AStar)
% This function plots the characteristic lines generated by flow through a
% converging-diverging nozzle. This function is intended to be an
% educational tool for AE302 (High Speed Aerodynamics) at San Diego State
% University, NOT an engineering tool.
%
% NOTE: The format of each data structure input into this function is
% assumed, make sure the fields and subfield of the data structures are
% named as indicated in ComputeMinimumNozzleContour.m
%
% Input:
%   Fig    -- Handle to the figure you want to plot to
%
%   Node   -- Data structure containing all characteristic nodes.
%
%   CPlus  -- Data structure containing nodes along each CPlus lines. 
%
%   CMinus -- Data structure containing nodes along each CMinus lines.
%
%   NozzleNodes -- Data structure containing nodes along the nozzle wall.
%
%   AStar  -- Throat "area". This is used to deterine starting point of 
%              the expansion fan and the nozzle wall.
%
% Outputs: NONE

% Just double check the input figure is actually selected to plot to
Fig;

% Plot the 

end